---
- name: "Checking OS Details"
  hosts: all
  #  remote_user: root
  #  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - debug:
        msg:
          - "Hostname {{ hostvars[inventory_hostname].ansible_ssh_host }}"
          - "ansible_distribution {{ hostvars[inventory_hostname].ansible_distribution }}"
          - "major version {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
          - "version {{ hostvars[inventory_hostname].ansible_distribution_version }}"
